In [43]:
import pandas as pd
import numpy as np

In [58]:
kfold_recs = pd.read_csv("kfold_recs.csv")
kfold_preds = pd.read_csv("kfold_preds.csv")

In [59]:
kfold_recs = kfold_recs.rename(columns = {'Unnamed: 0': 'id'})
kfold_preds = kfold_preds.rename(columns = {'Unnamed: 0': 'id'})

In [60]:
ks = [f'k{i}' for i in range(5)]

In [61]:
# score all

kfold_score = kfold_preds.copy()
for k in ks:
    kfold_score[k] = np.where(kfold_score[k] == kfold_score['class'], 1, 0)

kfold_score['sum'] = kfold_score.loc[:,ks].sum(axis=1)

In [83]:
# score all plant-diseased

kf_hd = kfold_preds.copy()

kf_hd.drop(kf_hd[kf_hd['class'] == 0].index, inplace=True)

for k in ks:
    kf_hd.drop(kf_hd[(kf_hd['class'] == 1) & (kf_hd[k] == 0)].index, inplace=True)

kf_hd_sc = kf_hd.copy()

for k in ks:
    kf_hd_sc[k] = np.where(kf_hd_sc[k] == kf_hd_sc['class'], 1, 0)
    
kf_hd_sc['sum'] = kf_hd_sc.loc[:,ks].sum(axis=1)

In [84]:
kf_hd

,id,path,type,class,k0,k1,k2,k3,k4
0,7,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1.0,1.0,1.0,1.0,1.0
1,747,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,1,1.0,1.0,1.0,1.0,1.0
2,12,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1.0,1.0,1.0,1.0,1.0
3,82,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1.0,1.0,1.0,1.0,1.0
4,56,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,2.0,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...
679,183,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,1,1.0,1.0,1.0,1.0,1.0
680,550,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,1,2.0,2.0,2.0,2.0,2.0
681,35,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1.0,1.0,1.0,1.0,1.0
684,21,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1.0,1.0,2.0,2.0,1.0
686,64,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1.0,1.0,1.0,1.0,1.0

In [85]:
kf_hd_sc

,id,path,type,class,k0,k1,k2,k3,k4,sum
0,7,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,0,0,0,0,0,0
1,747,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,1,1,1,1,1,1,5
2,12,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,0,0,0,0,0,0
3,82,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,0,0,0,0,0,0
4,56,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,1,1,1,1,1,5
...,...,...,...,...,...,...,...,...,...,...
679,183,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,1,1,1,1,1,1,5
680,550,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,1,0,0,0,0,0,0
681,35,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,0,0,0,0,0,0
684,21,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,0,0,1,1,0,2
686,64,D:\gyeongsang_22_10_14\PATCHES\STACK_75_BANDS_...,hdr,2,0,0,0,0,0,0

In [90]:
kf_hd_sc.loc[kf_hd_sc['class'] == 1]['sum'].value_counts()
# kf_hd_sc.loc[kf_hd_sc['class'] == 1].sort_values(by=['sum'])

5    242
0     13
4     12
3      6
1      4
2      1
Name: sum, dtype: int64